### ISSUE TITLE
SpawnersAPI Errors

### ISSUE THREAD

**Issue by ashyvaane** [LeandroTheDev/spawners_api#2]
Hello! SpawnersAPI is throwing a lot of errors on my server, I've attached client and server logs for your reference.
[Client Logs.zip](https://github.com/user-attachments/files/16831520/Client.Logs.zip)
[Server Logs.gz](https://github.com/user-attachments/files/16831521/Server.Logs.gz)

**Comment by LeansBoboDev** [comment]
Thanks for the reported, fixed in 1.0.9

**Comment by ashyvaane** [comment]
Thank you!
